# --- Experiment configurations --------------------------------------------------------------------

# experiment name, used as folder name
experiment_name: lr_red_512_bs

# files to specify training, validation and test basins (relative to code root or absolute path)
train_basin_file: "/home/wuhlmann/BA/data/processed_data/test_splits/train_basin_ids.txt"
validation_basin_file: "/home/wuhlmann/BA/data/processed_data/test_splits/val_basin_ids.txt"
test_basin_file: "/home/wuhlmann/BA/data/processed_data/test_splits/test_basin_ids.txt"

# training, validation and test time periods (format = 'dd/mm/yyyy')
per_basin_train_periods_file: "/home/wuhlmann/BA/data/processed_data/test_splits/train_q_filter.pkl"
per_basin_validation_periods_file: "/home/wuhlmann/BA/data/processed_data/test_splits/val_q_filter.pkl"
per_basin_test_periods_file: "/home/wuhlmann/BA/data/processed_data/test_splits/test_q_filter.pkl"

# which GPU (id) to use [in format of cuda:0, cuda:1 etc, or cpu, mps or None]
device: cuda:0

# --- Validation configuration ---------------------------------------------------------------------

# specify after how many epochs to perform validation
validate_every: 1

# specify how many random basins to use for validation
validate_n_random_basins: 86

# specify which metrics to calculate during validation (see neuralhydrology.evaluation.metrics)
# this can either be a list or a dictionary. If a dictionary is used, the inner keys must match the name of the
# target_variable specified below. Using dicts allows for different metrics per target variable.
metrics:
  - NSE
  - KGE
  - MSE
  - RMSE

# --- Model configuration --------------------------------------------------------------------------

# base model type [lstm, ealstm, cudalstm, embcudalstm, mtslstm]
# (has to match the if statement in modelzoo/__init__.py)
model: ealstm

# prediction head [regression]. Define the head specific parameters below
head: regression

# ----> Regression settings <----
output_activation: linear

# ----> General settings <----

# Number of cell states of the LSTM
hidden_size: 256

# Initial bias value of the forget gate
initial_forget_bias: 3

# Dropout applied to the output of the LSTM
output_dropout: 0.4

# --- Training configuration -----------------------------------------------------------------------

# specify optimizer [Adam]
optimizer: Adam

# specify loss [MSE, NSE, RMSE]
loss: NSE 

# specify learning rates to use starting at specific epochs (0 is the initial learning rate)
learning_rate:
  0: 0.0005
  10: 0.0001
  20: 0.00001

# Mini-batch size
batch_size: 512

# Number of training epochs
epochs: 30

# If a value, clips the gradients during training to that norm.
clip_gradient_norm: 1

# Defines which time steps are used to calculate the loss. Can't be larger than seq_length.
# If use_frequencies is used, this needs to be a dict mapping each frequency to a predict_last_n-value, else an int.
predict_last_n: 1

# Length of the input sequence
# If use_frequencies is used, this needs to be a dict mapping each frequency to a seq_length, else an int.
seq_length: 365

# Number of parallel workers used in the data pipeline
num_workers: 24

# Log the training loss every n steps
log_interval: 5

# If true, writes logging results into tensorboard file
log_tensorboard: True

# If a value and greater than 0, logs n random basins as figures during validation
log_n_figures: 1

# Save model weights every n epochs
save_weights_every: 5

# --- Data configurations --------------------------------------------------------------------------

# which data set to use [camels_us, camels_gb, global, hourly_camels_us]
dataset: lamah_b

# Path to data set root
data_dir: /home/wuhlmann/BA/data/raw_data/2_LamaH-CE_daily/

dynamic_inputs:
  - prec
  - 2m_temp_mean

static_attributes: 
  - area_calc
  - elev_mean
  - elev_ran
  - slope_mean
  - p_mean
  - et0_mean
  - arid_1
  - p_season
  - hi_prec_fr
  - hi_prec_du
  - lo_prec_fr
  - lo_prec_du
  - frac_snow
  - agr_fra
  - bare_fra
  - forest_fra
  - glac_fra
  - lake_fra
  - urban_fra
  - lai_max
  - lai_diff
  - gvf_max
  - gvf_diff
  - bedrk_dep
  - soil_poros
  - soil_condu
  - sand_fra
  - silt_fra
  - clay_fra
  
# which columns to use as target
target_variables:
  - qobs 

# clip negative predictions to zero for all variables listed below. Should be a list, even for single variables.
clip_targets_to_zero:
  - qobs

train_data_file: /home/wuhlmann/BA/data/cached_datasets/q_filter_with_fallback.p

seed: 1277