batch_size: 512
clip_gradient_norm: 1
clip_targets_to_zero:
- qobs
commit_hash:
data_dir: /home/wuhlmann/BA/data/raw_data/2_LamaH-CE_daily
dataset: lamah_b
device: cuda:0
dynamic_inputs:
- prec
- 2m_temp_mean
epochs: 30
experiment_name: q_pred_landcover
head: regression
hidden_size: 256
img_log_dir: 
  /storage/vast-gfz-hpc-01/home/wuhlmann/BA/test_runs/runs/q_pred_landcover_0903_135428/img_log
initial_forget_bias: 3
learning_rate:
  0: 0.001
  10: 0.0005
  20: 0.0001
log_interval: 5
log_n_figures: 1
log_tensorboard: true
loss: NSE
metrics:
- NSE
- KGE
- MSE
- RMSE
model: ealstm
num_workers: 16
number_of_basins: 686
optimizer: Adam
output_activation: linear
output_dropout: 0.4
package_version: 1.12.0
predict_last_n: 1
run_dir: 
  /storage/vast-gfz-hpc-01/home/wuhlmann/BA/test_runs/runs/q_pred_landcover_0903_135428
save_train_data: true
save_weights_every: 1
seed: 1277
seq_length: 365
static_attributes:
- area_calc
- elev_mean
- elev_ran
- slope_mean
- p_mean
- et0_mean
- arid_1
- p_season
- hi_prec_fr
- hi_prec_du
- lo_prec_fr
- lo_prec_du
- frac_snow
- agr_fra
- bare_fra
- forest_fra
- glac_fra
- lake_fra
- urban_fra
- lai_max
- lai_diff
- gvf_max
- gvf_diff
- bedrk_dep
- soil_poros
- soil_condu
- sand_fra
- silt_fra
- clay_fra
target_variables:
- qobs
test_basin_file: 
  /home/wuhlmann/BA/repo/lamah-ce_lstm/data/splits_incl_landcover/test_basin_ids.txt
test_end_date: 31/12/2019
test_start_date: 01/01/1981
train_basin_file: 
  /home/wuhlmann/BA/repo/lamah-ce_lstm/data/splits_incl_landcover/train_basin_ids.txt
train_dir: 
  /storage/vast-gfz-hpc-01/home/wuhlmann/BA/test_runs/runs/q_pred_landcover_0903_135428/train_data
train_end_date: 31/12/2019
train_start_date: 01/01/1981
validate_every: 1
validate_n_random_basins: 86
validation_basin_file: 
  /home/wuhlmann/BA/repo/lamah-ce_lstm/data/splits_incl_landcover/val_basin_ids.txt
validation_end_date: 31/12/2019
validation_start_date: 01/01/1981
